services:
  - type: web
    name: teja-rishika-wedding
    env: static
    buildCommand: npm install --include=dev && node ./node_modules/vite/bin/vite.js build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
